CREATE TABLE "GCG_3968_Daily_Ship"(
 "TERMINAL" CHAR(3),
 "ORDER_NO" CHAR(7),
 "ORDER_LINE" CHAR(4),
 "DESCRIPTION" CHAR(30),
 "QTY_SHIPPED" NUMERIC(13,4),
 "QTY_ORDERED" NUMERIC(13,4),
 "PREV_SHIPPED" NUMERIC(13,4));
